"""Constants."""

BUILD_DIR = "_build"

TINY_LENGTH = 0.001  # 1μm

COLOR_ITEM = (64, 164, 223)

CUTOUT_FILLET_RADIUS = 6
FINGER_CUTOUT_DIAMETER = 24
FINGER_CUTOUT_RADIUS = FINGER_CUTOUT_DIAMETER / 2
FINGER_CUTOUT_FILLET_RADIUS = FINGER_CUTOUT_RADIUS - TINY_LENGTH
MAX_WALL_THICKNESS = 2.5
